### ISSUE TITLE
Android option

### ISSUE THREAD

**Issue by husnainali09** [arsi-apli/UltraRemote#1]
Is there anyway I can view this on android ?

**Comment by arsi-apli** [comment]
An Android app needs to be written. I've already thought about it, but I don't know if there would be any interest. I don't need it, but if there's interest, I can look at it sometime..
Basically all we need is a new UI and to convince android to run the algorithm in the background.

**Comment by husnainali09** [comment]
Alternatively a http/webserver UI would be as useful so it can be accessed via phone and remotely like what mainsail does for klipper
