### ISSUE TITLE
Printer cannot be seen on LAN

### ISSUE THREAD

**Issue by JakubCoderCze** [arsi-apli/UltraRemote#2]
Hi, when I try to find the printer it only works when I'm on wifi, is there any way to make it work over LAN when I'm on the same router as the wifi?

**Comment by arsi-apli** [comment]
It is programmed to work over LAN as well. I would need more information from you, the operating system and if the LAN is the only network adapter that you have active at the time. 
Alternatively, if you can handle WireShark, try to see if the UDP broadcast from the adapter goes to 255.255.255.255 port 3000 in the packet body should be M99999. A response should then be returned from the printer..

**Comment by arsi-apli** [comment]
I remembered that if you have IPV6 enabled, java default starts net services under IPV6. Try running it like this:
`java -Djava.net.preferIPv4Stack=true  -jar UltraRemote-01.00-shaded.jar`
