### ISSUE TITLE
HOW TO OPEN

### ISSUE THREAD

**Issue by rexxyz** [arsi-apli/UltraRemote#6]
hello i want to ask, how to open this file,cause i see dont have file .jar to compile java file or any other. i running on windows. thanks

**Comment by Allariah** [comment]
You need to run the JAR file from the [Releases Page](https://github.com/arsi-apli/UltraRemote/releases/tag/1.0.2) if you don't want to compile it yourself.


Then you need to open a command line and run "java -jar "PATHTOYOURJAVAFILE""

For example mine looks like: 
java -jar "C:\Users\Me\Downloads\UltraRemote-01.00-shaded.jar"
