### ISSUE TITLE
Home Assistant Support

### ISSUE THREAD

**Issue by V3L** [arsi-apli/UltraRemote#9]
As per the title, would you be able to make this compatible with Home Assistant. This would allow it to the information to be used to drive other workflows, or allow the information to be easily viewed on mobile etc

**Comment by V3L** [comment]
I’ll be honest also, I don’t know much about the dev side of Home Assistant, but it does have MQTT support. It does sound like the sort of thing that would normally be possible. It might help address the request from a few people to have this accessible on mobile as well. I may look into the process of creating a Home Assistant Add-On, but no promises as it isn’t my usual area of expertise.

If it is something you figure out and you want some testing I’m happy to help out!

**Comment by a0s** [comment]
@arsi-apli 

>You need to send a UDP packet to port 3000, M66666 XXXX where XXXX is the port of the MQTT server. 

Where do you get this information?

**Comment by arsi-apli** [comment]
wireshark revealed it to me😉
